### ISSUE TITLE
Toast should show up from the bottom of the screen

### ISSUE THREAD

**Issue by android-bee** [EgorBo/Toasts.Forms.Plugin#41] opened 2015-10-07 06:25 UTC
Hi ,

I am using this toasts.forms.plugin, i need this toast message to show up at the bottom of the screen. just need to know where exactly i should change the position of the toast.
please help!!
Thanks in advance.

**Comment by adamped** [comment] 2016-01-22 04:46
Duplicate of: https://github.com/EgorBo/Toasts.Forms.Plugin/issues/8

Please follow that thread for any progress.

**Closed by adamped** 2016-01-22 04:46 UTC
